language: cpp
compiler:
  - gcc
  - clang
#script:
 # - ./run_build.sh
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y llvm-3.4 llvm-3.4-dev; fi
  - sudo apt-get install python3
install:
   - pip install numpy
   - pip install matplotlib
   - pip install scipy
   #- if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then sudo apt-get install python-matplotlib; fi
   #- if [[ $TRAVIS_PYTHON_VERSION == "3.2" ]]; then sudo apt-get install python3-dev python3-numpy; fi
before_script:
  - travis_retry bundle
  - if [ $TRAVIS_OS_NAME == linux ]; then travis_retry ./configure --llvm-config llvm-config-3.4; fi
   
notifications:
  email:
    - r.deepu@fz-juelich.de
  on_success: change
  on_failure: always
  #on_start: false
