language: cpp
compiler:
  - gcc
  - clang
#script:
 # - ./run_build.sh
before_install:
  - echo $LANG
  - echo $LC_ALL
  
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y llvm-3.4 llvm-3.4-dev; fi
  #- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install python3 ipython3 python3-matplotlib python3-matplotlib-tk; fi
  #- sudo apt-get install -y python3 ipython3 python3-matplotlib python3-matplotlib-tk
  - sudo apt-get install -y python3 ipython3
  # For NEST ConnPlotter tutorial
  #- sudo apt-get install -y texlive-multirow texlive-pdfcrop
  #Clang
  - sudo apt-get install clang-analyzer indent
  # Required by Topographica
  - sudo apt-get install xorg-x11-server-Xvfb pylint pyflakes
  # Required by NEST, PyNN and Topographica
  - sudo apt-get install python-devel numpy scipy python-virtualenv python-matplotlib python-matplotlib-tk
  # Required by Sumatra and PyNN
  - sudo apt-get install python-coverage python-nose python-setuptools
  - sudo apt-get install mpi4py-openmpi
  #python 3
  - sudo apt-get install python3 python3-devel python3-numpy python3-scipy python3-nose python3-coverage python3-Cython
  # Needed for documentation, e.g. NEST examples
  - sudo apt-get install texlive texlive-latex ghostscript
  #Build dependencies for NEST
  - sudo apt-get install autoconf automake libtool libtool-ltdl-devel
  - sudo apt-get install gsl-devel openmpi-devel readline-devel Cython
  #Build dependencies for Sumatra
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install Django django-tagging python-django python-django-tagging python-httplib2 python-simplejson GitPython pysvn; fi
  #Build dependencies for PyNN
  - sudo apt-get install python-cheetah python-jinja2 python-mock
  #Build dependencies for Topographica
  - sudo apt-get install tkinter gmpy python-imaging python-imaging-tk
  
  - sudo apt-get install cvs e2fsprogs-devel gettext-devel glib2-devel gpm-devel groff libssh2-devel slang-devel ncurses-devel check check-devel
  
  #- sudo apt-get install build-essential autoconf automake libtool libltdl7-dev 
  #- sudo apt-get install libreadline6-dev libncurses5-dev libgsl0-dev python-all-dev python-numpy python-scipy python-matplotlib ipython 
#install:
 #  - pip install numpy
#   - pip install matplotlib
#   - pip install scipy
   #- if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then sudo apt-get install python-matplotlib; fi
   #- if [[ $TRAVIS_PYTHON_VERSION == "3.2" ]]; then sudo apt-get install python3-dev python3-numpy; fi
#before_script:
#  - travis_retry bundle
 # - if [ $TRAVIS_OS_NAME == linux ]; then travis_retry ./configure --llvm-config llvm-config-3.4; fi
script:
  - ./run_build.sh  
notifications:
  email:
    - r.deepu@fz-juelich.de
  on_success: change
  on_failure: always
  #on_start: false
